### ISSUE TITLE
ㄷㄷ

### ISSUE THREAD

**Issue by Kitsunetic** [young31/AIRUSH2021#1]
우와 이미지랑 자연어 둘 다 2등이신가요... ㄷㄷ

저도 이미지는 제한 때문에 할 수 있는게 한정적인게 좀 아쉽다고 생각해요

**Comment by young31** [comment]
제한돼있는게 좀 색다르긴 하더군요 ㅎㅎ
심님은 더 올라가실  겁니다~!
저는 이미지 프로젝트가 거의 첨이라.. 많이 배워보겠습니다 ㅎㅎ
